language: node_js
sudo: required
dist: trusty
node_js: '7'
env: CXX=g++-4.8
services:
  - mongodb
  - docker
before_install:
  - docker pull trufflesuite/ganache-cli
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli
script:
- npm run test
