language: node_js
sudo: required
dist: trusty
node_js: '7'
env: CXX=g++-4.8
services:
  - mongodb
  - docker
before_install:
  - docker pull trufflesuite/ganache-cli
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli
  - docker build -t ethereumclassic/explorer .
  - docker run -t -p 3000:3000 -p 8545:8545  ethereumclassic/explorer app.js
script:
- npm run test
