language: node_js
sudo: required
dist: trusty
node_js: '7'
env: CXX=g++-4.8
services:
  - mongodb
  - docker
before_script: docker run -d -p 8545:8545 ethereumjs/testrpc:latest
script:
- npm run start
