version: '3'
services:
  app:
    build: .
    command: npm start
    restart: always
    environment:
      MONGODB_URI: 'mongodb://db/explorerDB'
    ports:
      - '3000:3000'
    depends_on:
      - db
  sync:
    build: .
    command: npm run sync
    restart: always
    environment:
      MONGODB_URI: 'mongodb://db/explorerDB'
    depends_on:
      - db
  stats:
    build: .
    command: npm run stats
    restart: always
    environment:
      MONGODB_URI: 'mongodb://db/explorerDB'
    depends_on:
      - db
  price:
    build: .
    command: npm run price
    restart: always
    environment:
      MONGODB_URI: 'mongodb://db/explorerDB'
    depends_on:
      - db
  richlist:
    build: .
    command: npm run rich
    restart: "no"
    environment:
      MONGODB_URI: 'mongodb://db/explorerDB'
    depends_on:
      - db
  db:
    image: mongo
